name: Pull-Infinite
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  pull:
    runs-on: ubuntu-18.04
    steps:
      - name: pull image
        run: |
          while true
          do
            echo "Pulling image..."
            docker pull ghcr.io/panchalshubham/owncloud:latest
            docker image rm ghcr.io/panchalshubham/owncloud:latest
            echo "y" | docker image prune -a
            echo ""
            echo ""
          done


